Change conf.example.json directory to correct one
taigaio/taiga-doc pull request #7
Opened 2021-06-03 16:55 UTC by nuokh

Looks like the folder /dist/ in taiga-front got renamed to /conf/.

2022-07-03 11:54 UTC, Justman10000 commented
@bameda

2023-02-27 09:42 UTC, yamila-moreno requested changes
Hi @Justman10000 
thank you for your contribution! We're currently preparing a release and doing a clean-up of pull-requests.

Your changes are mostly correct, but currently the repository changed and now there are some conflicts. If you'd like to keep this contribution, you can rebase `main` and remove conflicts.

I've left some changes to be made in order to merge this to main. If you want to continue with this PR, I'd like to help you; otherwise, we can made these fixes.

Cheers!

2023-02-27 09:42 UTC, yamila-moreno commented on setup-production.adoc
> +From https://github.com/kaleidos-ventures/taiga-front[taiga-front] download the file `conf/conf.example.json` and rename it:
good catch, thanks!

2023-02-27 09:42 UTC, yamila-moreno commented on setup-production.adoc
> +mv conf/conf.example.json conf/conf.json
this change is ok, given the original code, but it really should be:
`mv conf.example.json conf.json`

2023-02-27 09:42 UTC, yamila-moreno commented on setup-production.adoc
> +Edit it with your own configuration and map the file into `/taiga-front/conf/config.py`.
this sentence is no longer in the current `main` but the documentation bug is still present in the current branch.

This part is about mapping "conf.json" not, "config.py". And, according to [`docker-compose.yml`](https://github.com/kaleidos-ventures/taiga-docker/blob/main/docker-compose.yml#L110) it should be mapped into a different path.

2023-02-27 10:44 UTC, nuokh commented
Thanks for the offer, but I decided not to move further with our Taiga project due to too many issues in our test phase, so I am kind of "out of the loop" :-) Great to hear the project is picking up some steam again, tho!

2023-02-27 11:11 UTC, yamila-moreno commented
Hi @nuokh thanks for your answer. I totally understand if you have your focus in a different part. We'll take care of these changes.

And you're welcome in the community whenever you want :)

Cheers!!

2023-02-27 11:11 UTC, closed without merging